### ISSUE TITLE
Unable to render feedback link in template

### ISSUE THREAD

**Issue by macin** [cosmocode/dokuwiki-plugin-feedback#23]
### Issue Description

I have added following code (as per docs)
```
<?php
/** @var action_plugin_feedback $feedback */
$feedback = plugin_load('action', 'feedback');
if($feedback) $feedback->tpl();
?>
```
To the advanced configuration in admin panel 

![image](https://github.com/cosmocode/dokuwiki-plugin-feedback/assets/1422747/4afe7a8d-1911-41cd-9647-0e959d963bc0)

and I get following error 

![image](https://github.com/cosmocode/dokuwiki-plugin-feedback/assets/1422747/7643a606-672d-4ac0-ad07-ec7e4cd4b9bf)

version used is Kaos 6a.

It also does not work in side panel, so tried the footer... which would probbaly be even better if it worked ;)

**Comment by splitbrain** [comment]
The warning you get is issued by the "advanced" plugin and has nothing to do with the feedback plugin.

The code will only output anything when the apropriate feedback managers are configured
